eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka123@localhost:8761/eureka
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.1.120:3306/oa_dev?useSSL=false&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useInformationSchema=true&autoReconnect=true&failOverReadOnly=false
      username: root
      password: Root1234.
      # 初始化连接大小
      initialSize: 0
      # 连接池最大使用连接数量
      maxActive: 20
      # 连接池最小空闲
      minIdle: 0
      # 获取连接最大等待时间
      maxWait: 60000
      validationQuery: SELECT 1
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 25200000
      # 打开removeAbandoned功能
      removeAbandoned: true
      # 1800秒，也就是30分钟
      removeAbandonedTimeout: 1800
      # 关闭abanded连接时输出错误日志
      logAbandoned: true
      # 监控数据库
      filters: stat
      stat-view-servlet:
        url-pattern: /druid/*